#!/usr/bin/env bash

set -e

VENV_DIR="venv"

sudo apt update
echo "Verificando Dependências..."

check_command() {
    command -v "$1" >/dev/null 2>&1
}

echo "🔎 Verificando pip3..."

if check_command pip3; then
    echo "✅ pip3 já está instalado."
else
    echo "⚙️ Instalando pip3..."
    sudo apt update
    sudo apt install -y python3-pip

    if ! check_command pip3; then
        echo "❌ Erro ao instalar pip3."
        exit 1
    fi
fi

echo "🔎 Instalando suporte a ambiente virtual..."
sudo apt install -y \
    python3-venv \
    python3-dev \
    python3-tk \
    python3-full \
    scrot \
    libx11-dev \
    libxtst-dev \
    libxrandr-dev \
    libpng-dev \
    libjpeg-dev

# Criar ambiente virtual se não existir
if [ ! -d "$VENV_DIR" ]; then
    echo "📦 Criando ambiente virtual..."
    python3 -m venv "$VENV_DIR"

    if [ $? -ne 0 ]; then
        echo "❌ Erro ao criar ambiente virtual."
        exit 1
    fi
fi

# Ativar ambiente virtual
echo "🚀 Ativando ambiente virtual..."
source "$VENV_DIR/bin/activate"

# Atualizar pip dentro do venv
echo "⬆️ Atualizando pip, setuptools e wheel..."

pip uninstall -y pyautogui pyscreeze pillow opencv-python 2>/dev/null || true

pip install --upgrade pip setuptools wheel

pip install --no-cache-dir pillow
pip install --no-cache-dir opencv-python
pip install --no-cache-dir pyautogui
# echo "🔎 Verificando PyAutoGUI..."

# if python -m pip show pyautogui >/dev/null 2>&1; then
#     echo "✅ PyAutoGUI já está instalado."
# else
#     echo "📦 Instalando PyAutoGUI..."
#     pip install pyautogui

#     if [ $? -ne 0 ]; then
#         echo "❌ Erro ao instalar PyAutoGUI."
#         exit 1
#     fi
# fi

python ./bot_atualizador.py